filecoin-project/ec-gpu

- .circleci/config.yml
- ec-gpu-gen/Cargo.toml
- ec-gpu-gen/src/cl/test.cl
- ec-gpu-gen/src/lib.rs
It's now possible to run the tests also on CUDA.
All this sadly needs a lot of boilerplate code. It seems like rust-gpu-tools could need some improvements on that front.
> test: add CUDA support to tests

- ec-gpu-gen/Cargo.toml
The `cuda` and `opencl` features are only needed for testing.
> fix: no default features

- .circleci/config.yml
- README.md
- ec-gpu-gen/Cargo.toml
- ec-gpu-gen/src/lib.rs
The current features are only used for the tests, make this clearer
by prefixing them with `tests-`.
> fix: rename features

- ec-gpu-gen/src/lib.rs
The AMD OpenCL compiler doesn't support assignments with the struct
initializer syntax (`{ … }`). So intead of using defines for intitializing
field elements, define them as constants instead.
It changes from e.g.
#define Fr_ONE ((Fr){ { 4294967294, 1, 215042, 1485092858, 3971764213, 2576109551, 2898593135, 405057881 } })
to
CONSTANT Fr Fr_ONE = { { 4294967294, 1, 215042, 1485092858, 3971764213, 2576109551, 2898593135, 405057881 } };
Fixes https://github.com/filecoin-project/neptune/issues/118.
> fix: make it more AMD GPU compatible

- .circleci/config.yml
Sometimes CI is failing, I suspect an environment issue. Print the
GPU's UUID to see if it always happens on the same GPU.
> chore: list GPUs on CI

- ec-gpu-gen/src/fft.rs
- ec-gpu-gen/src/multiexp.rs
The refactoring that moved code from bellperson into this library lead
to a regression. Accidentally OpenCL was using 32-bit limbs, which
should lead to less performance than using 64-bit limbs.
The CUDA code path was always using the expected 32-bit limbs. Even
if it doesn't look like it from this change, it was the case as the
CUDA kernels are compiled at compile-time, the limb size is correctly
specified in build.rs.
> fix: make OpenCL use 64-bit limbs

- .circleci/config.yml
- ec-gpu-gen/build.rs
Due to the CUDA kernel compilation the documentation creation on
docs.rs fails. With this commit we skip that step for the docs.rs
platform, so that the documentation is successfully built there.
Fixes #19.
> chore: make sure that the documention is available on doc.rs

- ec-gpu-gen/Cargo.toml
BREAKING CHANGE: the upgraded dependencies define traits
If you have traits from different versions of dependencies, then things
will break. Hence those updates will be in a breaking change release.
> chore: update dependencies

- ec-gpu-gen/Cargo.toml
- ec-gpu-gen/benches/multiexp.rs
It is now possible to benchmark multiexp. The largest benchmark likely
needs more memory than the GPU has. This is done in order to make sure
that splitting the data into two runs also performs well.
With the default features, the benchmark is run on CUDA. To make sure
it is run with OpenCL only you can either set `EC_GPU_FRAMEWORK=opencl`
or disable the `cuda` feature via.
cargo bench --no-default-features --features multiexp,opencl multiexp
> feat: add a benchmark for multiexp

- ec-gpu-gen/Cargo.toml
- ec-gpu-gen/src/multiexp.rs
The chunk size calculation used to be based on the number of CUDA cores.
Instead use a fixed number of threads that is then split nicely into
blocks for optimal performance.
Benchmarks have been run on Quadro RTX 6000, GeForce RTX 2080 Ti and
GeForce RTX 3090 to make sure there isn't any big regression on CUDA
or OpenCL. In some limited cases, the performance is less good. Though
for large number of terms, things got significantly faster, which is
what this library is optimized for.
Below are the numbers of those runs. For each graphics card the
multiexp benchmark was run twice. For each size the better (lower)
number of each run was used. It compares the runtime prior to this
commit (old) to the runtime with this commit applied (new). The
cases where either old or new are better are …
> fix: simplify chunk size and window size calculation of multiexp

- .circleci/config.yml
When run in parallel, tests sometime fail with "No GPU found".
> chore: run tests on CI sequentially

- ec-gpu-gen/build.rs
- ec-gpu-gen/src/fft.rs
- ec-gpu-gen/src/multiexp.rs
- ec-gpu-gen/src/program.rs
The OpenCL kernel source could be generated at run-time, but with this
change it makes it more similar to the CUDA version, where we need to
compile the kernel at compile-time. This is to improve the symmetry
between those features and should also simplify the code for future
changes.
> fix: generate OpenCL source at compile time

- ec-gpu/src/lib.rs
The ec-gpu traits are re-organized.
BREAKING CHANGE: The `GpuEngine` trait is removed, as it was specific
to pairing friendlt elliptic curves.
The `GpuField` trait gains a new method called `sub_field_name`, which
only matters for extension fields. It has a default implementation, so
existing implementations don't need to change.
A new trait called `GpuName` is introduced, which every `GpuField` needs
to implement. It contains the name of the object it's implemented for,
which is then used in the generated source code as identifier.
> feat: re-organize ec-gpu traits

- ec-gpu-gen/src/cl/ec.cl
- ec-gpu-gen/src/cl/multiexp.cl
In the GPU code for elliptic curve operatations we use the affine and the jacobian representation of a point. Rename the jacobian one from `_projective` to `_jacobian` to make clear that it is *not* the standard projective representation, but the jacobian representation.
I've made this change after a discussion with @DrPeterVanNostrand quite some time ago, but then forgot to PR it.
> fix: name jacobian representation more explicitly

- Cargo.toml
Using resolver version 2 (which is default in Rust editiion 2021), it is possible to run `cargo build --target wasm32-unknown-unknown` without any failures. Note that even before this change it was possible when `ec-gpu-gen` was used as a dependency, but with this change it becomes more apparent.
The problem was that the `rand` dev-dependency was enabling the `std` feature, which then led to `ff` pulling is `getrandom`, which has problems to be compiled to `wasm32-unknown-unknown` without setting the `js` feature.
Closes #32.
> fix: enable dependency resolver v2 for workspace

- ec-gpu-gen/Cargo.toml
- ec-gpu/Cargo.toml
As the resolver v2 is used on the workspace, it makes sense to upgrade all crates to Rust edition 2021.
BREAKING CHANGE: Switch to Rust edition 2021
> fix: update to Rust 2021 edition

- ec-gpu-gen/Cargo.toml
- ec-gpu-gen/src/multiexp_cpu.rs
Performance for multiexp on the CPU was checked, there is no regression.
This update is needed as bitvec 0.22.3 is requiring funty 1.2 which was yanked.
> chore: upgrade to bitvec 1.0.1 (#39)

- gpu-tests/Cargo.toml
With this upgrade, criterion doesn't have a dependency on `csv` anymore, hence we don't need to increase the minimum support Rust version, due to the `csv` v1.2.0 release.
> chore: update to criterion 0.4

- ec-gpu-gen/src/cl/multiexp.cl
In the multiexp kernel, we calculate the number of elements per group. The division might have a remainder, hence ceil the result, so that we can be sure that there are enough groups to fit all elements.
In the current code, that ceil operation is performed by casting the number of groups to a float, so that it's a floating point division. Then the result is rounded up (ceiled).
The problem is that floating point numbers don't have arbitrary precision. If you calculate 131076643 / 327.0 with an arbitrary precision calculator, then the result is 400846.003058. That one rounded up gives the expected result of 400847.
Though with 32-bit IEEE-754 floating point numbers, 400846.003058 has the same byte representation as 400846 (0x48C3B9C0). This means that a call to `ceil`, will have the wrong …
> fix: multiexp kernel, ceil correctly

- release.toml
The default behaviour of cargo release changed in v0.25. When there is a workspace, it now consolidates all changes into a single commit by default. This means that the commit message can't contain the version number of a specific crate.
With adding a relase.toml file with the `consolidate-commits = false` options restores the old behaviour and you get separate commits. We release those two crates separatly anyway.
I decided to use the release.toml file instead of putting it into the Cargo.toml, to make it clearer that we use custom cargo-release options. This can easily be overlooked if it's just a value in the Cargo.toml.
> chore: make version part of the release commit
